### PR TITLE
JavaScript BigInt to WebAssembly i64 integration to phase 3

### PR DESCRIPTION
**Pull request by chicoxyzzy**
per November 12, 2019 meeting

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
cc @xtuc (can't add you as a reviewer)

**Comment by chicoxyzzy** [comment]
BTW @xtuc should we add you as a co-champion?

**Comment by xtuc** [comment]
yeah, I'm happy to continue pushing it. If it's fine with @littledan?

**Comment by littledan** [comment]
Yes, congratulations!

**Pull request merged**
