### PR TITLE
Add "affected specs" column to finished proposal list

### PR DESCRIPTION
**Pull request by dschuff**
Addresses #140

### CODE REVIEW

**Review by ericprud — APPROVED** [review]
I believe that's what I need for publishing FPWD.

tx

**Review by BertsLifee — APPROVED** [review]

**Comment by trastvolt** [comment]
dschuff-patch-1

**Comment by dschuff** [comment]
Yeah, this could be merged, although I'm not sure it's necessary. since I wrote this I've also added changelog sections in the JS API and Web API documents, which are ultimately what horizontal reviewers are more likely to want to see.

**Comment by dschuff** [comment]
I guess it doesn't hurt though, I'll go ahead and merge it.

**Pull request merged**
