### PR TITLE
Move spec status

### PR DESCRIPTION
**Pull request by rossberg**
Move status of spec to "Accepted", which seems more accurate than Stage 2. Logically it should be at least as far along as any proposals that have been accepted into it.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
What's the motivation behind having spec as a proposal?

**Comment by rossberg** [comment]
Good question, I don't know how it ended up here in the first place.

**Comment by chicoxyzzy** [comment]
Initially I added it to proposals table because of label on  https://github.com/WebAssembly/proposals/issues/15. IMO it's better to delete spec from proposals table in readme completely. WDYT?

**Comment by rossberg** [comment]
SGTM

**Comment by chicoxyzzy** [comment]
Oops, I accidentally made [commit](
https://github.com/WebAssembly/proposals/commit/103b6e31db493604fba4cbad3fc355ecf5ceca1a) instead of PR. I can revert it if necessary. @binji WDYT?

**Comment by binji** [comment]
No, it's fine, this change lgtm.

**Pull request merged**
