### PR TITLE
Add type imports proposal

### PR DESCRIPTION
**Pull request by rossberg**
...as per A Coruna meeting.

### CODE REVIEW

**Comment by tlively** [comment]
Wasn't it decided to move this to phase 1? Or am I mixing this up with a different proposal?

**Comment by rossberg** [comment]
Maybe, my memory is shaky. We surely decided that for function references.

Or does splitting off something from a proposal that already is at stage 1 (in this case, the GC proposal) imply that it is at stage 1 as well?

**Comment by tlively** [comment]
Stage 0 is essentially nothing, so the fact that we decided anything at all with respect to type imports suggests to me that it should be stage 1. I couldn't really find confirmation of this in the notes, though.

**Comment by binji** [comment]
Yes, this would be phase 1. No vote is required for phase 0.

**Comment by rossberg** [comment]
Okay, moved it.

**Pull request merged**
