### PR TITLE
Add Custom Annotations proposal

### PR DESCRIPTION
**Pull request by chicoxyzzy**
@rossberg please confirm that proposal is in phase 0

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Merging per https://github.com/WebAssembly/meetings/blob/master/2018/CG-03-06.md#annotation-syntax-for-the-text-format

**Comment by chicoxyzzy** [comment]
Oh, or is it at phase 1? 🤔

**Comment by chicoxyzzy** [comment]
Yes, seems like it's at phase 1 https://github.com/WebAssembly/meetings/blob/master/2018/CG-04.md#annotations-for-the-wasm-text-format

**Comment by rossberg** [comment]
Sorry, missed this somehow. Yes, it's phase 1.

**Pull request merged**
