### PR TITLE
Add gc-js-customization as a phase 0 proposal

### PR DESCRIPTION
**Pull request by tlively**
The GC subgroup decided to split the customization of JS accessors and prototypes for GC objects out into a separate proposal.

### CODE REVIEW

**Comment by trastvolt** [comment]
tlively-patch-2

**Review by dschuff — APPROVED** [review]

**Comment by Daasin** [comment]
Would there be any new update on this being approved & merged by any chance? 😅 @dschuff @rossberg

**Comment by dschuff** [comment]
Sorry I guess I assumed Thomas could just merge the PR when he was ready. I'll take care of that. the repo (https://github.com/webassembly/gc-js-customization) looks to be live already.

**Comment by tlively** [comment]
Oops, yeah, not sure why I didn't just merge this before. Thanks, @dschuff!

**Comment by dschuff** [comment]
Does this proposal have a formal champion?

**Comment by tlively** [comment]
Nope, but I think that's ok for a phase 0 proposal. You can list "The GC Subgroup" for now, I guess.

**Comment by dschuff** [comment]
Yeah, I think that's fine for phase 0, adding the subgroup makes sense.

**Comment by Daasin** [comment]
> Does this proposal have a formal champion?

I would have assumed it was Asumu Takikawa, but not 100% sure on that

**Comment by tlively** [comment]
Well that explains why I never merged this!

**Pull request closed without merging**
