### PR TITLE
Withdraw Unmanaged Closures proposal

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Related discussion https://github.com/WebAssembly/proposals/issues/6

This PR also adds two new pages: [inactive proposals](https://github.com/WebAssembly/proposals/blob/6d5b7f397fbf4299a84071ab471841030872c572/inactive-proposals.md) and [finished proposals](https://github.com/WebAssembly/proposals/blob/6d5b7f397fbf4299a84071ab471841030872c572/finished-proposals.md).

### CODE REVIEW

**Comment by binji** [comment]
For others' information: This matches the way tc39/proposals does it https://github.com/tc39/proposals. We have a smaller list, so we could probably keep them separate, but maybe it's nicer this way.

**Comment by chicoxyzzy** [comment]
Yes, I can add inactive proposals list to `Readme.md` if others think that it'll be better to have one `.md` file

**Comment by binji** [comment]
We can always change it later if need be. Let's land as-is.

**Comment by binji** [comment]
Seems like there are no concerns, merging.

**Pull request merged**
